name: eunice-mr-review
description: automatic technical debt analysis on merge requests using real gitlab data

components:
  - name: detect_debt
    type: AgentComponent
    agent: eunice-debt-detector
    model: claude-sonnet-4-5
    prompt: |
      analyze this merge request for technical debt patterns.
      
      merge request context: ${AI_FLOW_CONTEXT}
      
      ## your task
      
      use nia to analyze the changed files:
      1. use manage_resource to check if this repo is indexed
      2. use nia_grep and search to find code patterns
      3. identify technical debt:
         - high complexity (cyclomatic > 10)
         - dead code (no references found via nia)
         - outdated dependencies
         - missing test coverage
      
      ## critical rules
      
      - only flag issues with concrete evidence from nia
      - cite specific line numbers
      - calculate realistic severity (1-10)
      - never guess or hallucinate
      
      ## output format
      
      return json:
      ```json
      {
        "findings": [
          {
            "type": "high_complexity",
            "file": "auth.py",
            "lines": "45-120",
            "severity": 8,
            "evidence": {
              "description": "nested conditionals, cyclomatic complexity high",
              "nia_search_results": "no similar clean patterns found",
              "source": "nia semantic search"
            }
          }
        ]
      }
      ```
  
  - name: analyze_impact
    type: AgentComponent
    agent: eunice-impact-analyzer
    model: claude-opus-4-6
    prompt: |
      calculate real business impact using gitlab api data.
      
      technical debt findings: ${detect_debt.output}
      project: ${CI_PROJECT_ID}
      merge request: ${CI_MERGE_REQUEST_IID}
      
      ## your task
      
      for each finding:
      
      1. use python to query gitlab api (you have eunice-data-engine installed):
         ```python
         from eunice.gitlab_client import EuniceGitLabClient
         from eunice.cost_calculator import *
         import os
         
         client = EuniceGitLabClient(
             url=os.getenv('GITLAB_URL'),
             token=os.getenv('GITLAB_TOKEN')
         )
         config = EuniceConfig('eunice.yml')
         
         # get real metrics (last 30 days)
         commits = client.get_file_commits(project_id, file_path, 30)
         mrs = client.get_mrs_with_file_changes(project_id, file_path, 30)
         bugs = client.get_bug_issues_with_time_tracking(project_id, file_path, 30)
         pipelines = client.get_pipelines_touching_file(project_id, file_path, 30)
         
         # calculate costs
         velocity_cost = calculate_annual_velocity_cost(
             commit_count_monthly=len(commits),
             avg_review_time_minutes=avg([client.calculate_mr_review_time(mr) for mr in mrs]),
             bug_hours_tracked=sum([b['hours_spent'] for b in bugs]),
             ci_failure_count_monthly=len([p for p in pipelines if p.status == 'failed']),
             config=config,
             bug_hours_window_days=30
         )
         
         roi_data = calculate_roi(
             annual_savings=velocity_cost['annual_cost_usd'],
             effort_hours=estimate_fix_effort(lines_of_code, config),
             config=config
         )
         ```
      
      2. return transparent analysis with data sources:
         ```json
         {
           "file": "auth.py",
           "annual_cost_usd": 5040,
           "cost_breakdown_usd": {
             "review_overhead": 1890,
             "bug_fixes": 1350,
             "ci_failures": 1800
           },
           "measured_inputs": {
             "commits_last_30_days": 12,
             "avg_mr_review_minutes": 14,
             "bug_hours_tracked": 18,
             "ci_failures_count": 2
           },
           "gitlab_data_sources": {
             "commits": ["abc123", "def456"],
             "mrs": [123, 456],
             "bugs": [789, 012],
             "pipelines": [345, 678]
           },
           "assumptions_used": {
             "dev_hourly_rate_usd": 75,
             "source": "eunice.yml"
           },
           "roi": {
             "roi_multiplier": 140,
             "effort_hours": 6,
             "priority_score": 9.2
           }
         }
         ```
      
      ## critical requirements
      
      - use REAL gitlab api data, not estimates
      - link to all data sources (commits, mrs, issues, pipelines)
      - show calculation formulas
      - cite assumptions from eunice.yml
      - make everything reproducible
  
  - name: post_feedback
    type: AgentComponent
    agent: eunice-orchestrator
    model: claude-opus-4-6
    prompt: |
      create merge request feedback and issues.
      
      findings: ${detect_debt.output}
      impact analysis: ${analyze_impact.output}
      project: ${CI_PROJECT_ID}
      mr: ${CI_MERGE_REQUEST_IID}
      
      ## your task
      
      1. post inline mr comment with transparent breakdown:
      
      ```markdown
      ## ðŸ’° technical debt analysis: {file}
      
      ### annual impact: ${annual_cost_usd}
      
      #### measured from gitlab (last 30 days)
      | metric | value | source |
      |--------|-------|--------|
      | commits | {count} | [see commits]({gitlab_link}) |
      | avg mr review | {minutes} min | [mrs]({mr_links}) |
      | bug fix hours | {hours} hrs | [issues]({issue_links}) |
      | ci failures | {count} | [pipelines]({pipeline_links}) |
      
      #### cost breakdown
      | category | calculation | annual cost |
      |----------|-------------|-------------|
      | review overhead | {commits}/mo Ã— {minutes} Ã— ${rate}/hr Ã— 12 | ${amount} |
      | bug fixes | {hours}/30d Ã— ${rate}/hr Ã— 12.17 | ${amount} |
      | ci failures | {failures}/mo Ã— {hours} Ã— ${rate}/hr Ã— 12 | ${amount} |
      | **total** | | **${total}** |
      
      #### assumptions (from eunice.yml)
      - dev rate: ${rate}/hr (source: {source})
      - avg ci debug time: {hours} hrs
      
      #### fix effort: {hours} hours
      **roi: {multiplier}x**
      
      #### recommended fix
      1. {step 1}
      2. {step 2}
      3. {step 3}
      
      ---
      ðŸ“Š priority score: {score}/10  
      ðŸ” [full analysis]({analysis_url})  
      âš™ï¸ [edit assumptions](eunice.yml)
      ```
      
      2. if annual_cost >= $5000 OR roi >= 50x:
         - create gitlab issue with same content
         - assign to file owner (via git blame)
         - add labels: eunice-debt, priority::high
      
      3. if slack enabled:
         - post summary to #eunice-alerts channel
         - include link to mr and issue
      
      ## tone
      
      friendly, data-driven, helpful. never judgmental.

routing:
  - from: start
    to: detect_debt
  
  - from: detect_debt
    to: analyze_impact
    condition: detect_debt.output.findings.length > 0
  
  - from: detect_debt
    to: end
    condition: detect_debt.output.findings.length == 0
  
  - from: analyze_impact
    to: post_feedback
  
  - from: post_feedback
    to: end

triggers:
  - merge_request.created
  - merge_request.updated
